apiVersion: apps/v1
kind: Deployment
metadata:
  name: playlist-recommender-api
  namespace: boyan
  labels:
    app: playlist-recommender-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: playlist-recommender-api
  template:
    metadata:
      labels:
        app: playlist-recommender-api
    spec:
      # 添加初始化容器，等待 ML 作业完成
      initContainers:
      - name: wait-for-ml-job
        image: bitnami/kubectl:latest
        command:
        - /bin/sh
        - -c
        - |
          echo "Waiting for ML job to complete..."
          until kubectl -n boyan get job playlist-recommender-ml -o jsonpath='{.status.succeeded}' | grep -q 1; do
            echo "ML job is still running, waiting..."
            sleep 10
          done
          echo "ML job completed successfully!"
      containers:
      - name: api
        image: quay.io/johnnybyzhang/playlist-recommender-api:latest
        env:
        - name: MODEL_VERSION
          value: "0.2"
        volumeMounts:
        - name: dataset-volume
          mountPath: /app/model
        ports:
        - containerPort: 5000
      volumes:
      - name: dataset-volume
        persistentVolumeClaim:
          claimName: playlist-recommender-pvc
      # 添加 serviceAccount 以便 initContainer 可以访问 Kubernetes API
      serviceAccountName: job-reader
