apiVersion: v1
kind: Service
metadata:
  name: playlist-recommender-api
  namespace: boyan
spec:
  selector:
    app: playlist-recommender-api
  ports:
    - protocol: TCP
      port: 52009
      targetPort: 5000
  type: ClusterIP
