apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: playlist-recommender
  namespace: boyan
spec:
  project: boyan-project
  source:
    repoURL: 'https://github.com/Johnnybyzhang/CS401-CICD.git'
    targetRevision: HEAD
    path: k8s
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: boyan
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
