apiVersion: batch/v1
kind: Job
metadata:
  name: playlist-recommender-ml
  namespace: boyan
  labels:
    app: playlist-recommender
    component: ml
    part-of: playlist-recommender
     tier: backend
    spec:
      template:
        spec:
          containers:
          - name: ml
            image: quay.io/johnnybyzhang/playlist-recommender-ml:latest
            volumeMounts:
            - name: dataset-volume
              mountPath: /app/dataset
            - name: spotify-dataset
              mountPath: /app/dataset/dataset.csv
              subPath: dataset.csv
          restartPolicy: Never
          volumes:
          - name: dataset-volume
            persistentVolumeClaim:
              claimName: playlist-recommender-pvc
          - name: spotify-dataset
            hostPath:
              path: /home/datasets/spotify/2023_spotify_ds1.csv
              type: File
      backoffLimit: 3
