apiVersion: batch/v1
kind: Job
metadata:
  name: playlist-recommender-ml
  namespace: boyan
  labels:
    app: playlist-recommender
    component: ml
    part-of: playlist-recommender
    tier: backend
spec:
  template:
    spec:
      containers:
      - name: ml
        image: quay.io/johnnybyzhang/playlist-recommender-ml:latest
        command:
        - /bin/sh
        - -c
        - |
          python train_model.py
          # 创建完成标记文件
          touch /app/data/job-completed.txt
        volumeMounts:
        - name: dataset-volume
          mountPath: /app/data
      restartPolicy: Never
      volumes:
      - name: dataset-volume
        persistentVolumeClaim:
          claimName: playlist-recommender-pvc
  backoffLimit: 3
