apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: playlist-recommender-pvc
  namespace: boyan
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard
  selector:
    matchLabels:
      namespace: boyan
