[project]
name = "ml"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "flask>=3.1.0",
    "mlxtend>=0.23.4",
    "pandas>=2.2.3",
    "requests>=2.32.3",
]
